### PR TITLE
Polymer 2.0, 'file' and 'files' properties

### PR DESCRIPTION
**Pull request by mkazlauskas**
This PR updates to Polymer 2.0 and adds more functionality to enable declarative usage via bindings.

Breaking change: file selection event changed to `file-changed` and `files-changed`.

### CODE REVIEW

**Comment by jefBinomed** [comment]
Why did you start from master ? I have created a https://github.com/binomed/granite-file-reader/tree/2.0-preview branch for polymer2. And As this repo is just a fork of original granite component, I recommand you to contribute to this PR : https://github.com/LostInBrittany/granite-file-reader/pull/2. 

regards

**Comment by mkazlauskas** [comment]
I didn't start from master, just merged 2.0-preview to my master. It doesn't mean it can't be merged to yours or LostInBrittany's 2.0-preview. Polymer's 2.0 is released, but the convention is to have hybrid elements for the time being. I can convert it to hybrid quite easily if you or LostInBritanny were interested in putting this to master.

**Comment by jefBinomed** [comment]
I think that @lostInBritanny want to propose their component in Hybrid mode indeed ! I have to see with him what he really want and when he want to propose the granite library in Hybrid mode for polymer 2

**Comment by jefBinomed** [comment]
@mkazlauskas did you try add your commits to the original repository ? because @LostInBrittany has already migrate it's component to Polymer2 so my pr is not needed anymore :'(

**Comment by mkazlauskas** [comment]
I have not, I guess let's just leave it as a fork.

**Pull request closed without merging**
